# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'label.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_window(object):
    def setupUi(self, window):
        window.setObjectName("window")
        window.resize(768, 617)
        window.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(window)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(130, 20, 491, 191))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(150, 170, 511, 91))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(150, 270, 511, 91))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(150, 370, 511, 91))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(150, 470, 511, 91))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton.raise_()
        self.label.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 768, 26))
        self.menubar.setObjectName("menubar")
        window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(window)
        self.statusbar.setObjectName("statusbar")
        window.setStatusBar(self.statusbar)

        self.retranslateUi(window)
        QtCore.QMetaObject.connectSlotsByName(window)

    def retranslateUi(self, window):
        _translate = QtCore.QCoreApplication.translate
        window.setWindowTitle(_translate("window", "Anaconda"))
        self.label.setText(_translate("window", "<html><head/><body><p align=\"center\"><span style=\" font-size:48pt; font-weight:600; color:#00ff00;\">ANACONDA</span></p></body></html>"))
        self.pushButton.setWhatsThis(_translate("window", "<html><head/><body><p align=\"center, color:#000000;\"><br/></p></body></html>"))
        self.pushButton.setText(_translate("window", "PushButton"))
        self.pushButton_2.setWhatsThis(_translate("window", "<html><head/><body><p align=\"center, color:#000000;\"><br/></p></body></html>"))
        self.pushButton_2.setText(_translate("window", "PushButton"))
        self.pushButton_3.setWhatsThis(_translate("window", "<html><head/><body><p align=\"center, color:#000000;\"><br/></p></body></html>"))
        self.pushButton_3.setText(_translate("window", "PushButton"))
        self.pushButton_4.setWhatsThis(_translate("window", "<html><head/><body><p align=\"center, color:#000000;\"><br/></p></body></html>"))
        self.pushButton_4.setText(_translate("window", "PushButton"))
